# Site settings
title: Scoop Themes

author: Moe Shaaban
author_url: http://www.twitter.com/1moex

permalink: /templates/:title/

email: support@scoopthemes.com

description: > # this means to ignore newlines until "baseurl:"
  Free Premium Bootstrap Templates . Themes . Components . UI Kits. Carefully Crafted Like No Other.

site_solgan: Free Premium Bootstrap Templates and Themes

copyrights: All Copyrights Reserved For ScoopThemes Inc.

baseurl: "" # the subpath of your site, e.g. /blog/
#highlighter: rouge

url: "www.scoopthemes.com" # the base hostname & protocol for your site

twitter_username: ScoopThemes
github_username:  ScoopThemes
facebook_username: ScoopThemes

# Build settings
markdown: kramdown
