# Site settings
title: Scoop Themes

author: Moe Shaaban
author_url: http://www.twitter.com/mshaaban0

permalink: /templates/:title/

email: support@scoopthemes.com

description: > # this means to ignore newlines until "baseurl:"
  Free Premium Bootstrap 3 Templates & Themes high crafted like never before in the open source community, 
  All our templates and themes are open source under the MIT license, free to use. Enjoy!

site_solgan: Free Premium Bootstrap Templates and Themes

copyrights: All Copyrights Reserved For ScoopThemes Inc.

baseurl: "" # the subpath of your site, e.g. /blog/
#highlighter: rouge

url: "www.scoopthemes.com" # the base hostname & protocol for your site

twitter_username: ScoopThemes
github_username:  ScoopThemes
facebook_username: ScoopThemes

# Build settings
markdown: kramdown
